version: '3.8'

services:
  mongodb:
    container_name: mongo
    image: mongo:4.4.3
    ports:
      - 27017:27017
    env_file:
      - .dtransfer.env
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: