version: '3.8'

networks:
  web:
    name: web
    external: true
  database:
    name: database
    external: false

services:
  mongodb:
    container_name: mongo
    image: mongo:4.4.3
    command: [--auth]
    networks:
      - database
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  # consumer:
  #   container_name: consumer
  #   image: middleware-consumer:latest
  #   networks:
  #     - web
  #     - database
  #   env_file:
  #     - .consumer.env

  # dtransfer:
  #   container_name: dtransfer
  #   image: middleware-dtransfer:latest
  #   networks:
  #     - web
  #     - database
  #   env_file:
  #     # As this is for local development use both
  #     - .dtransfer.prod.env
  #     - .dtransfer.dev.env
  #   volumes:
  #     # Useful for development purposes
  #     - ./data:/app/data/
  #     # Relevant CSVs
  #     - ./local:/app/local/

volumes:
  mongodb: